version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - checkout
      - run: bundle check || bundle install
  test:
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - checkout
      - run: bundle exec rspec spec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
