version: 2.1

jobs:
  test:
    parameters:
      ruby:
        type: string
    docker:
      - image: 'cimg/ruby:<< parameters.ruby >>'
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: ['2.7', '3.1']
