version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: |
            gem install bundler && \
            bundle check || bundle install
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
